### ISSUE TITLE
Use default php mail function

### ISSUE THREAD

**Issue by gwbonline** [GawainLynch/bolt-extension-boltforms#11]
Is there a way to use this extension with the default php mail function? I have to setup mailoptions, but my provider says I have to use php's built in mail funcion. When I don't set mailoptions, the extension says I have to... With a test script I verified that the default mail funcion works. When I don't set mailoptions in the config file, the extension does nothing.

**Comment by GawainLynch** [comment]
That is in Bolt itself, it just uses the same mailer object that Bolt does [in app/confi/config.yml](https://github.com/bolt/bolt/blob/release/2.1/app/config/config.yml.dist#L253-L255)

**Comment by gwbonline** [comment]
I didn't have those options because of an older config file... And yes, it works now!

**Comment by GawainLynch** [comment]
Ah yeah, that has tripped me up before too :grin:

**Comment by gwbonline** [comment]
Something else (and little I think)... Where can I set the width of the fields?

**Comment by GawainLynch** [comment]
In CSS… Each field ID is created (by Symfony) as `formname_fieldname`.

**Comment by gwbonline** [comment]
Yes, just found out via the source code. Added some lines to the css file and it looks good. Thanks anyway.
