### ISSUE TITLE
Send notification not implemendted...

### ISSUE THREAD

**Issue by gwbonline** [GawainLynch/bolt-extension-boltforms#13]
We talked earlies about this extension. It works just fine... except for the send notification. This was fixed in https://github.com/GawainLynch/bolt-extension-boltforms/commit/12a4f03b0c36f156e98849295d16d76f04e3b480 but not implemented yet.

I just installed the extension for an other website and the send notification worked after I uploaded the newer file myself.

**Comment by GawainLynch** [comment]
Forgive me, I have just landed in Australia and am a bit jet lagged. :grin: But I am missing what is, um, missing. That change you linked is in v2.1.4.

**Comment by gwbonline** [comment]
That is strange... When I installed the extension and tested it, the send notification wasn't displayed after sending a message. Then I remembered your fix and replaced the files. After that, I did see the send notification. To be clear: it was a new installation of the extension (I took the newest version) on a different server.

**Comment by GawainLynch** [comment]
Lots of fixes that should include this and more in v2.3.0
