### ISSUE TITLE
Recaptcha doesn't detect SSL so browser hides it (disables form)

### ISSUE THREAD

**Issue by aerth** [GawainLynch/bolt-extension-boltforms#14]
Works http, not https.
if ($_SERVER['HTTPS'] != "on")  maybe?
There is an option in the recaptcha php library that allows if SSL=TRUE. not sure where boltforms is sending the request to the library though

**Comment by GawainLynch** [comment]
It works for me. The setting you refer to is in the old version of the library, BoltForms 2.1.4 has the newer one.

**Comment by aerth** [comment]
Thank you!
