### ISSUE TITLE
Issue with Datetime field if link to contenttype or database enabled

### ISSUE THREAD

**Issue by helman** [GawainLynch/bolt-extension-boltforms#17]
Hi @GawainLynch ,

I did a quick fix for this issue on 107 after JSON checking in Database.php writeToContenttype method 

```php
            // Datetime instance value
            if ($value instanceof \DateTime) {
                $data[$key] = $value->format('c');
            }
```

Cheers,
Helman

**Comment by GawainLynch** [comment]
Thanks. @jadwigo submitted this in #16 and is in 2.1.5. :grin:
