### ISSUE TITLE
Error when updating in Bolt back-end

### ISSUE THREAD

**Issue by evertalbers** [GawainLynch/bolt-extension-boltforms#2]
Not a very clear bugreport probably, I cannot see the error notification well in the Bolt back-end, but I get this error when I hit the update extension-button:

```
Whoops \ Exception \ ErrorException (E_ERROR)

Call to undefined method Composer\DependencyResolver\Operation\UpdateOperation::getPackage()

          
/domains/streeff.nl/test/extensions/installer.php

namespace Bolt\Composer;
 
class ExtensionInstaller
{
    public static function handle($event)
    {
        try {
            $installedPackage = $event->getOperation()->getPackage();
        } catch (\Exception $e) {
            return;
```
and in the left column I also see 
```
0.
…/­extensions/­installer.php9

 ```
somewhere. 

I have used it in a test-site, so for now I'll just go back to that other Bolt-form extension.

**Comment by GawainLynch** [comment]
That is actually coming from Bolt core...  I am just about to get on a plane, but should be able to look deeper in a few hours!

**Comment by GawainLynch** [comment]
Yes, Ross committed a fix for this a while ago.  It affected all extension.

**Comment by evertalbers** [comment]
Thanks
