### ISSUE TITLE
Redirects hiding flash messages

### ISSUE THREAD

**Issue by xiaohutai** [GawainLynch/bolt-extension-boltforms#283]
I have troubles showing (custom) flash messages (from the `session.flashbag`).

So in order to fix the flooding of the system log, there were some return responses introduced:

- https://github.com/bolt/boltforms/commit/e254959fd53e6175f093412e33284231a50f0ff0
- https://github.com/bolt/boltforms/commit/131976a9f58f00031f53f55f1b3ccd575ad4d47d

Removing the `return` from `return $response->send();
` in `src/Submission/Handler/Redirect.php` makes the messages appear, and everything seems to be working fine again:

- https://github.com/bolt/boltforms/blob/4.2/src/Submission/Handler/Redirect.php#L62
- https://github.com/bolt/boltforms/blob/4.2/src/Submission/Handler/Redirect.php#L76

**However**, this will start flooding the system log again (which is preferable to no messages shown at all).

Removing the `Exception` simply breaks the form. Only with an `Exception` or `exit`/`die`, does it do what I want. But relying on this as a control structure seems like a super bad idea.

See https://github.com/bolt/boltforms/blob/4.2/src/Submission/Processor/Redirect.php#L90-L95

But I also have a feeling that something else might break because of these fixes. So, I'm not sure how to go from here.

**Comment by bobdenotter** [comment]
See also #257

**Comment by xiaohutai** [comment]
Fixed in `4.3.0-beta.1`, but the caveats still apply.
