### ISSUE TITLE
Dynamic email notif configuration

### ISSUE THREAD

**Issue by EzeRangel** [GawainLynch/bolt-extension-boltforms#38]
Hello, I have played with Bolt Forms a few days and I think I'm stuck.

How can I add/edit the email notification dynamically? Maybe via a local extension?

Example: Based in a selected choice in the form, I need to change the main email recipient or add a cc email.

I tryed to use PRE_SUBMIT event and add a cc_name/cc_email to the notification configuration related to the form but nothing happens. Is there another way to do this?

**Comment by GawainLynch** [comment]
Ah, I think I fixed this yesterday in master… The logic was a bit messed up and I am doing some refactoring. I hope to have a new version out later today.

**Comment by GawainLynch** [comment]
Fixed in v2.3.0… Please let me know if there are further problems
