### ISSUE TITLE
Form Template override doesn't fall back to global templates

### ISSUE THREAD

**Issue by GDmac** [GawainLynch/bolt-extension-boltforms#41]
When only specifying global templates in the config,
a form doesn't fall back to the global ones.

https://github.com/GawainLynch/bolt-extension-boltforms/blob/master/src/Email.php#L81
There Email.php tries to fetch the mail template from the formConfig, 
but it will always have set a hardcoded default one from:
https://github.com/GawainLynch/bolt-extension-boltforms/blob/master/src/Config/FormConfig.php#L171

**Comment by GDmac** [comment]
Backtracing further: the processor seems to only provide the formDefinition, not the global stuff to formConfig.
https://github.com/GawainLynch/bolt-extension-boltforms/blob/master/src/Submission/Processor.php#L72

**Comment by GawainLynch** [comment]
Fixed in https://github.com/GawainLynch/bolt-extension-boltforms/commit/9225dd2d93f10e46d08b585df7ca01828b6fe6e4
