### ISSUE TITLE
Problem with uploading an image using BoltForms

### ISSUE THREAD

**Issue by DragonEW** [GawainLynch/bolt-extension-boltforms#7]
Hi, 
I have problem with uploading an image, in config i have a field with type: file. It renders nice html input type=file, but when i click submit, i've got exception: 
"Cannot use object of type Symfony\Component\HttpFoundation\File\UploadedFile as array"

Is it possible to upload files using this extension? It would be lovely, because I'm trying to add new records of contentype via frontend.

**Comment by GawainLynch** [comment]
Yeah, files is one that I hadn't had time to complete as it is a bit complex for security.

That said, it's something that people will want, so I will implement it soon :+1:

**Comment by Umbrielsama** [comment]
+1 for that feature!

**Comment by jadwigo** [comment]
just mentioning https://github.com/GawainLynch/bolt-extension-boltforms/pull/31 because that's about file uploads too

**Comment by GawainLynch** [comment]
Ugh… someone can't watch PR queues… Just merged #31 and I am going to do a bunch of updates (hopefully) this week and tag a new release when that's done!

**Comment by GawainLynch** [comment]
Implemented in v2.3
