### ISSUE TITLE
Deprecated message when sending mail

### ISSUE THREAD

**Issue by cooperaj** [GawainLynch/bolt-extension-boltforms#8]
I'm getting

```[DEPRECATED]: Previous message logged using deprecated log service: /extensions/vendor/bolt/boltforms/src/Email.php::199```

When using the email functionality for a form.

**Comment by GawainLynch** [comment]
I love the fact that I am the one that added that deprecation notice to Bolt core when I rewrote the logging component for 2.1…  Shall get onto it later today!

**Comment by GawainLynch** [comment]
Just pushed BoltForms 2.1.0 that should fix this.
